package test.serverframe.armc.server.manager.dao.mapper;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import test.serverframe.armc.server.manager.domain.DatumType;

import java.util.List;

public interface DatumTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @Delete({
        "delete from YEW_QB_CL_ZLFL",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @Insert({
        "insert into YEW_QB_CL_ZLFL (ID, FID, ",
        "FLLX, JGID, YHID, ",
        "FLMC, FLMS)",
        "values (#{id,jdbcType=VARCHAR}, #{fid,jdbcType=VARCHAR}, ",
        "#{fllx,jdbcType=VARCHAR}, #{jgid,jdbcType=VARCHAR}, #{yhid,jdbcType=VARCHAR}, ",
        "#{flmc,jdbcType=VARCHAR}, #{flms,jdbcType=CLOB})"
    })
    int insert(DatumType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @InsertProvider(type=DatumTypeSqlProvider.class, method="insertSelective")
    int insertSelective(DatumType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, FID, FLLX, JGID, YHID, FLMC, FLMS",
        "from YEW_QB_CL_ZLFL",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="FID", property="fid", jdbcType=JdbcType.VARCHAR),
        @Result(column="FLLX", property="fllx", jdbcType=JdbcType.VARCHAR),
        @Result(column="JGID", property="jgid", jdbcType=JdbcType.VARCHAR),
        @Result(column="YHID", property="yhid", jdbcType=JdbcType.VARCHAR),
        @Result(column="FLMC", property="flmc", jdbcType=JdbcType.VARCHAR),
        @Result(column="FLMS", property="flms", jdbcType=JdbcType.CLOB)
    })
    DatumType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @UpdateProvider(type=DatumTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DatumType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @Update({
        "update YEW_QB_CL_ZLFL",
        "set FID = #{fid,jdbcType=VARCHAR},",
          "FLLX = #{fllx,jdbcType=VARCHAR},",
          "JGID = #{jgid,jdbcType=VARCHAR},",
          "YHID = #{yhid,jdbcType=VARCHAR},",
          "FLMC = #{flmc,jdbcType=VARCHAR},",
          "FLMS = #{flms,jdbcType=CLOB}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(DatumType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    @Update({
        "update YEW_QB_CL_ZLFL",
        "set FID = #{fid,jdbcType=VARCHAR},",
          "FLLX = #{fllx,jdbcType=VARCHAR},",
          "JGID = #{jgid,jdbcType=VARCHAR},",
          "YHID = #{yhid,jdbcType=VARCHAR},",
          "FLMC = #{flmc,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(DatumType record);


    /**
     * @Descripttion  根据父id查询资料类型
     * @Author jiangyuanwei
     * @Date 2018/10/12 13:28
     * @Param [fid]
     * @Return
     **/
    @Select({
            "select",
            "ID, FID, FLLX, JGID, YHID, FLMC, FLMS",
            "from yew_qb_cl_zlfl",
            "where FID = #{fid,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="FID", property="fid", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLLX", property="fllx", jdbcType=JdbcType.VARCHAR),
            @Result(column="JGID", property="jgid", jdbcType=JdbcType.VARCHAR),
            @Result(column="YHID", property="yhid", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLMC", property="flmc", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLMS", property="flms", jdbcType=JdbcType.CLOB)
    })
    List<DatumType> selectDatumTypes(String fid);
    /**
     * @Descripttion  修改父id
     * @Author jiangyuanwei
     * @Date 2018/10/12 13:28
     * @Param [datumType]
     * @Return
     **/
    @Update({
            "update yew_qb_cl_zlfl",
            "set FID = #{fid,jdbcType=VARCHAR}",
            "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateDatumType(DatumType datumType);
    /**
     * @Descripttion  查询所有父资料类型
     * @Author jiangyuanwei
     * @Date 2018/10/12 13:28
     * @Param []
     * @Return
     **/
    @Select({
            "select",
            "ID, FID, FLLX, JGID, YHID, FLMC, FLMS,ID as rootId",
            "from yew_qb_cl_zlfl",
            "where FID is null"
    })
    @Results({
            @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="FID", property="fid", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLLX", property="fllx", jdbcType=JdbcType.VARCHAR),
            @Result(column="JGID", property="jgid", jdbcType=JdbcType.VARCHAR),
            @Result(column="YHID", property="yhid", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLMC", property="flmc", jdbcType=JdbcType.VARCHAR),
            @Result(column="FLMS", property="flms", jdbcType=JdbcType.CLOB)
    })
    List<DatumType> selectRoot();
    /**
     * @Descripttion  删除资料类型
     * @Author jiangyuanwei
     * @Date 2018/10/12 13:29
     * @Param [id, fid]
     * @Return
     **/
    @Delete({
            "delete from yew_qb_cl_zlfl",
            "where 1 = 1 and ID = #{id,jdbcType=VARCHAR} or FID = #{fid,jdbcType=VARCHAR}"
    })
    int deleteDatumType(@Param("id") String id, @Param("fid") String fid);
}