package test.serverframe.armc.server.manager.dao.mapper;

import org.apache.ibatis.jdbc.SQL;
import test.serverframe.armc.server.manager.domain.DatumReferencingAssociation;

public class DatumReferencingAssociationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLYYGL
     *
     * @mbg.generated
     */
    public String insertSelective(DatumReferencingAssociation record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("YEW_QB_CL_ZLYYGL");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getZlbh() != null) {
            sql.VALUES("ZLBH", "#{zlbh,jdbcType=VARCHAR}");
        }
        
        if (record.getYylx() != null) {
            sql.VALUES("YYLX", "#{yylx,jdbcType=VARCHAR}");
        }
        
        if (record.getYybh() != null) {
            sql.VALUES("YYBH", "#{yybh,jdbcType=VARCHAR}");
        }
        
        if (record.getCzr() != null) {
            sql.VALUES("CZR", "#{czr,jdbcType=VARCHAR}");
        }
        
        if (record.getCzsj() != null) {
            sql.VALUES("CZSJ", "#{czsj,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLYYGL
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DatumReferencingAssociation record) {
        SQL sql = new SQL();
        sql.UPDATE("YEW_QB_CL_ZLYYGL");
        
        if (record.getZlbh() != null) {
            sql.SET("ZLBH = #{zlbh,jdbcType=VARCHAR}");
        }
        
        if (record.getYylx() != null) {
            sql.SET("YYLX = #{yylx,jdbcType=VARCHAR}");
        }
        
        if (record.getYybh() != null) {
            sql.SET("YYBH = #{yybh,jdbcType=VARCHAR}");
        }
        
        if (record.getCzr() != null) {
            sql.SET("CZR = #{czr,jdbcType=VARCHAR}");
        }
        
        if (record.getCzsj() != null) {
            sql.SET("CZSJ = #{czsj,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}