package test.serverframe.armc.server.manager.dao.mapper;

import org.apache.ibatis.jdbc.SQL;
import test.serverframe.armc.server.manager.domain.DatumType;

public class DatumTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    public String insertSelective(DatumType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("YEW_QB_CL_ZLFL");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getFid() != null) {
            sql.VALUES("FID", "#{fid,jdbcType=VARCHAR}");
        }
        
        if (record.getFllx() != null) {
            sql.VALUES("FLLX", "#{fllx,jdbcType=VARCHAR}");
        }
        
        if (record.getJgid() != null) {
            sql.VALUES("JGID", "#{jgid,jdbcType=VARCHAR}");
        }
        
        if (record.getYhid() != null) {
            sql.VALUES("YHID", "#{yhid,jdbcType=VARCHAR}");
        }
        
        if (record.getFlmc() != null) {
            sql.VALUES("FLMC", "#{flmc,jdbcType=VARCHAR}");
        }
        
        if (record.getFlms() != null) {
            sql.VALUES("FLMS", "#{flms,jdbcType=CLOB}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLFL
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DatumType record) {
        SQL sql = new SQL();
        sql.UPDATE("YEW_QB_CL_ZLFL");
        
        if (record.getFid() != null) {
            sql.SET("FID = #{fid,jdbcType=VARCHAR}");
        }
        
        if (record.getFllx() != null) {
            sql.SET("FLLX = #{fllx,jdbcType=VARCHAR}");
        }
        
        if (record.getJgid() != null) {
            sql.SET("JGID = #{jgid,jdbcType=VARCHAR}");
        }
        
        if (record.getYhid() != null) {
            sql.SET("YHID = #{yhid,jdbcType=VARCHAR}");
        }
        
        if (record.getFlmc() != null) {
            sql.SET("FLMC = #{flmc,jdbcType=VARCHAR}");
        }
        
        if (record.getFlms() != null) {
            sql.SET("FLMS = #{flms,jdbcType=CLOB}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}