package test.serverframe.armc.server.manager.dao.mapper;

import org.apache.ibatis.jdbc.SQL;
import test.serverframe.armc.server.manager.domain.DatumState;

public class DatumStateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLZT
     *
     * @mbg.generated
     */
    public String insertSelective(DatumState record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("YEW_QB_CL_ZLZT");
        
        if (record.getZlbh() != null) {
            sql.VALUES("ZLBH", "#{zlbh,jdbcType=VARCHAR}");
        }
        
        if (record.getCgyybz() != null) {
            sql.VALUES("CGYYBZ", "#{cgyybz,jdbcType=DECIMAL}");
        }
        
        if (record.getTbyybz() != null) {
            sql.VALUES("TBYYBZ", "#{tbyybz,jdbcType=DECIMAL}");
        }
        
        if (record.getKwyybz() != null) {
            sql.VALUES("KWYYBZ", "#{kwyybz,jdbcType=DECIMAL}");
        }
        
        if (record.getPzbz() != null) {
            sql.VALUES("PZBZ", "#{pzbz,jdbcType=DECIMAL}");
        }
        
        if (record.getScbz() != null) {
            sql.VALUES("SCBZ", "#{scbz,jdbcType=DECIMAL}");
        }
        
        if (record.getYbcs() != null) {
            sql.VALUES("YBCS", "#{ybcs,jdbcType=DECIMAL}");
        }
        
        if (record.getXfcs() != null) {
            sql.VALUES("XFCS", "#{xfcs,jdbcType=DECIMAL}");
        }
        
        if (record.getCgcs() != null) {
            sql.VALUES("CGCS", "#{cgcs,jdbcType=DECIMAL}");
        }
        
        if (record.getZlzt() != null) {
            sql.VALUES("ZLZT", "#{zlzt,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YEW_QB_CL_ZLZT
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DatumState record) {
        SQL sql = new SQL();
        sql.UPDATE("YEW_QB_CL_ZLZT");
        
        if (record.getCgyybz() != null) {
            sql.SET("CGYYBZ = #{cgyybz,jdbcType=DECIMAL}");
        }
        
        if (record.getTbyybz() != null) {
            sql.SET("TBYYBZ = #{tbyybz,jdbcType=DECIMAL}");
        }
        
        if (record.getKwyybz() != null) {
            sql.SET("KWYYBZ = #{kwyybz,jdbcType=DECIMAL}");
        }
        
        if (record.getPzbz() != null) {
            sql.SET("PZBZ = #{pzbz,jdbcType=DECIMAL}");
        }
        
        if (record.getScbz() != null) {
            sql.SET("SCBZ = #{scbz,jdbcType=DECIMAL}");
        }
        
        if (record.getYbcs() != null) {
            sql.SET("YBCS = #{ybcs,jdbcType=DECIMAL}");
        }
        
        if (record.getXfcs() != null) {
            sql.SET("XFCS = #{xfcs,jdbcType=DECIMAL}");
        }
        
        if (record.getCgcs() != null) {
            sql.SET("CGCS = #{cgcs,jdbcType=DECIMAL}");
        }
        
        if (record.getZlzt() != null) {
            sql.SET("ZLZT = #{zlzt,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("ZLBH = #{zlbh,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}