package test.serverframe.armc.server.manager.dao.mapper;

import org.apache.ibatis.jdbc.SQL;
import test.serverframe.armc.server.manager.domain.Datum;

public class DatumSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QB_GYWB_ZL
     *
     * @mbg.generated
     */
    public String insertSelective(Datum record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("QB_GYWB_ZL");
        
        if (record.getZlbh() != null) {
            sql.VALUES("ZLBH", "#{zlbh,jdbcType=VARCHAR}");
        }
        
        if (record.getBt() != null) {
            sql.VALUES("BT", "#{bt,jdbcType=VARCHAR}");
        }
        
        if (record.getZtc() != null) {
            sql.VALUES("ZTC", "#{ztc,jdbcType=VARCHAR}");
        }
        
        if (record.getMmdj() != null) {
            sql.VALUES("MMDJ", "#{mmdj,jdbcType=VARCHAR}");
        }
        
        if (record.getCjr() != null) {
            sql.VALUES("CJR", "#{cjr,jdbcType=VARCHAR}");
        }
        
        if (record.getXgr() != null) {
            sql.VALUES("XGR", "#{xgr,jdbcType=VARCHAR}");
        }
        
        if (record.getMglx() != null) {
            sql.VALUES("MGLX", "#{mglx,jdbcType=VARCHAR}");
        }
        
        if (record.getFx() != null) {
            sql.VALUES("FX", "#{fx,jdbcType=VARCHAR}");
        }
        
        if (record.getHjid() != null) {
            sql.VALUES("HJID", "#{hjid,jdbcType=VARCHAR}");
        }
        
        if (record.getFlid() != null) {
            sql.VALUES("FLID", "#{flid,jdbcType=VARCHAR}");
        }
        
        if (record.getZlly() != null) {
            sql.VALUES("ZLLY", "#{zlly,jdbcType=VARCHAR}");
        }
        
        if (record.getFjbs() != null) {
            sql.VALUES("FJBS", "#{fjbs,jdbcType=DECIMAL}");
        }
        
        if (record.getKzbs() != null) {
            sql.VALUES("KZBS", "#{kzbs,jdbcType=DECIMAL}");
        }
        
        if (record.getCjsj() != null) {
            sql.VALUES("CJSJ", "#{cjsj,jdbcType=TIMESTAMP}");
        }
        
        if (record.getXgsj() != null) {
            sql.VALUES("XGSJ", "#{xgsj,jdbcType=TIMESTAMP}");
        }
        
        if (record.getXh() != null) {
            sql.VALUES("XH", "#{xh,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QB_GYWB_ZL
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Datum record) {
        SQL sql = new SQL();
        sql.UPDATE("QB_GYWB_ZL");
        
        if (record.getBt() != null) {
            sql.SET("BT = #{bt,jdbcType=VARCHAR}");
        }
        
        if (record.getZtc() != null) {
            sql.SET("ZTC = #{ztc,jdbcType=VARCHAR}");
        }
        
        if (record.getMmdj() != null) {
            sql.SET("MMDJ = #{mmdj,jdbcType=VARCHAR}");
        }
        
        if (record.getCjr() != null) {
            sql.SET("CJR = #{cjr,jdbcType=VARCHAR}");
        }
        
        if (record.getXgr() != null) {
            sql.SET("XGR = #{xgr,jdbcType=VARCHAR}");
        }
        
        if (record.getMglx() != null) {
            sql.SET("MGLX = #{mglx,jdbcType=VARCHAR}");
        }
        
        if (record.getFx() != null) {
            sql.SET("FX = #{fx,jdbcType=VARCHAR}");
        }
        
        if (record.getHjid() != null) {
            sql.SET("HJID = #{hjid,jdbcType=VARCHAR}");
        }
        
        if (record.getFlid() != null) {
            sql.SET("FLID = #{flid,jdbcType=VARCHAR}");
        }
        
        if (record.getZlly() != null) {
            sql.SET("ZLLY = #{zlly,jdbcType=VARCHAR}");
        }
        
        if (record.getFjbs() != null) {
            sql.SET("FJBS = #{fjbs,jdbcType=DECIMAL}");
        }
        
        if (record.getKzbs() != null) {
            sql.SET("KZBS = #{kzbs,jdbcType=DECIMAL}");
        }
        
        if (record.getCjsj() != null) {
            sql.SET("CJSJ = #{cjsj,jdbcType=TIMESTAMP}");
        }
        
        if (record.getXgsj() != null) {
            sql.SET("XGSJ = #{xgsj,jdbcType=TIMESTAMP}");
        }
        
        if (record.getXh() != null) {
            sql.SET("XH = #{xh,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("ZLBH = #{zlbh,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * @Descripttion 添加主题词
     * @Author jiangyuanwei
     * @Date 2018/10/9 13:04
     * @Param [record]
     * @Return
     **/
    public String updateZTC(Datum record) {
        SQL sql = new SQL();
        sql.UPDATE("qb_gywb_zl");

        if (record.getZtc() != null) {
            sql.SET("ZTC = #{ztc,jdbcType=VARCHAR}");
        }

        sql.WHERE("ZLBH = #{zlbh,jdbcType=VARCHAR}");

        return sql.toString();
    }
}