package test.serverframe.armc.server.manager.domain;

import java.math.BigDecimal;

public class DatumAccessory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.FJID
     *
     * @mbg.generated
     */
    private String fjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.ZLBH
     *
     * @mbg.generated
     */
    private String zlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.WJM
     *
     * @mbg.generated
     */
    private String wjm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.FJLX
     *
     * @mbg.generated
     */
    private String fjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.MTGS
     *
     * @mbg.generated
     */
    private String mtgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.ZS
     *
     * @mbg.generated
     */
    private BigDecimal zs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.WJDX
     *
     * @mbg.generated
     */
    private Long wjdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.CCLJ
     *
     * @mbg.generated
     */
    private String cclj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLFJ.FJWB
     *
     * @mbg.generated
     */
    private String fjwb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.FJID
     *
     * @return the value of QB_GYWB_ZLFJ.FJID
     *
     * @mbg.generated
     */
    public String getFjid() {
        return fjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.FJID
     *
     * @param fjid the value for QB_GYWB_ZLFJ.FJID
     *
     * @mbg.generated
     */
    public void setFjid(String fjid) {
        this.fjid = fjid == null ? null : fjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.ZLBH
     *
     * @return the value of QB_GYWB_ZLFJ.ZLBH
     *
     * @mbg.generated
     */
    public String getZlbh() {
        return zlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.ZLBH
     *
     * @param zlbh the value for QB_GYWB_ZLFJ.ZLBH
     *
     * @mbg.generated
     */
    public void setZlbh(String zlbh) {
        this.zlbh = zlbh == null ? null : zlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.WJM
     *
     * @return the value of QB_GYWB_ZLFJ.WJM
     *
     * @mbg.generated
     */
    public String getWjm() {
        return wjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.WJM
     *
     * @param wjm the value for QB_GYWB_ZLFJ.WJM
     *
     * @mbg.generated
     */
    public void setWjm(String wjm) {
        this.wjm = wjm == null ? null : wjm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.FJLX
     *
     * @return the value of QB_GYWB_ZLFJ.FJLX
     *
     * @mbg.generated
     */
    public String getFjlx() {
        return fjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.FJLX
     *
     * @param fjlx the value for QB_GYWB_ZLFJ.FJLX
     *
     * @mbg.generated
     */
    public void setFjlx(String fjlx) {
        this.fjlx = fjlx == null ? null : fjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.MTGS
     *
     * @return the value of QB_GYWB_ZLFJ.MTGS
     *
     * @mbg.generated
     */
    public String getMtgs() {
        return mtgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.MTGS
     *
     * @param mtgs the value for QB_GYWB_ZLFJ.MTGS
     *
     * @mbg.generated
     */
    public void setMtgs(String mtgs) {
        this.mtgs = mtgs == null ? null : mtgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.ZS
     *
     * @return the value of QB_GYWB_ZLFJ.ZS
     *
     * @mbg.generated
     */
    public BigDecimal getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.ZS
     *
     * @param zs the value for QB_GYWB_ZLFJ.ZS
     *
     * @mbg.generated
     */
    public void setZs(BigDecimal zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.WJDX
     *
     * @return the value of QB_GYWB_ZLFJ.WJDX
     *
     * @mbg.generated
     */
    public Long getWjdx() {
        return wjdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.WJDX
     *
     * @param wjdx the value for QB_GYWB_ZLFJ.WJDX
     *
     * @mbg.generated
     */
    public void setWjdx(Long wjdx) {
        this.wjdx = wjdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.CCLJ
     *
     * @return the value of QB_GYWB_ZLFJ.CCLJ
     *
     * @mbg.generated
     */
    public String getCclj() {
        return cclj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.CCLJ
     *
     * @param cclj the value for QB_GYWB_ZLFJ.CCLJ
     *
     * @mbg.generated
     */
    public void setCclj(String cclj) {
        this.cclj = cclj == null ? null : cclj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLFJ.FJWB
     *
     * @return the value of QB_GYWB_ZLFJ.FJWB
     *
     * @mbg.generated
     */
    public String getFjwb() {
        return fjwb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLFJ.FJWB
     *
     * @param fjwb the value for QB_GYWB_ZLFJ.FJWB
     *
     * @mbg.generated
     */
    public void setFjwb(String fjwb) {
        this.fjwb = fjwb == null ? null : fjwb.trim();
    }
}