package test.serverframe.armc.server.manager.domain;

import java.util.Date;

public class DatumReferencingAssociation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLYYGL.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLYYGL.ZLBH
     *
     * @mbg.generated
     */
    private String zlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLYYGL.YYLX
     *
     * @mbg.generated
     */
    private String yylx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLYYGL.YYBH
     *
     * @mbg.generated
     */
    private String yybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLYYGL.CZR
     *
     * @mbg.generated
     */
    private String czr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLYYGL.CZSJ
     *
     * @mbg.generated
     */
    private Date czsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLYYGL.ID
     *
     * @return the value of YEW_QB_CL_ZLYYGL.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLYYGL.ID
     *
     * @param id the value for YEW_QB_CL_ZLYYGL.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLYYGL.ZLBH
     *
     * @return the value of YEW_QB_CL_ZLYYGL.ZLBH
     *
     * @mbg.generated
     */
    public String getZlbh() {
        return zlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLYYGL.ZLBH
     *
     * @param zlbh the value for YEW_QB_CL_ZLYYGL.ZLBH
     *
     * @mbg.generated
     */
    public void setZlbh(String zlbh) {
        this.zlbh = zlbh == null ? null : zlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLYYGL.YYLX
     *
     * @return the value of YEW_QB_CL_ZLYYGL.YYLX
     *
     * @mbg.generated
     */
    public String getYylx() {
        return yylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLYYGL.YYLX
     *
     * @param yylx the value for YEW_QB_CL_ZLYYGL.YYLX
     *
     * @mbg.generated
     */
    public void setYylx(String yylx) {
        this.yylx = yylx == null ? null : yylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLYYGL.YYBH
     *
     * @return the value of YEW_QB_CL_ZLYYGL.YYBH
     *
     * @mbg.generated
     */
    public String getYybh() {
        return yybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLYYGL.YYBH
     *
     * @param yybh the value for YEW_QB_CL_ZLYYGL.YYBH
     *
     * @mbg.generated
     */
    public void setYybh(String yybh) {
        this.yybh = yybh == null ? null : yybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLYYGL.CZR
     *
     * @return the value of YEW_QB_CL_ZLYYGL.CZR
     *
     * @mbg.generated
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLYYGL.CZR
     *
     * @param czr the value for YEW_QB_CL_ZLYYGL.CZR
     *
     * @mbg.generated
     */
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLYYGL.CZSJ
     *
     * @return the value of YEW_QB_CL_ZLYYGL.CZSJ
     *
     * @mbg.generated
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLYYGL.CZSJ
     *
     * @param czsj the value for YEW_QB_CL_ZLYYGL.CZSJ
     *
     * @mbg.generated
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }
}