package test.serverframe.armc.server.manager.domain;

public class DatumState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.ZLBH
     *
     * @mbg.generated
     */
    private String zlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.CGYYBZ
     *
     * @mbg.generated
     */
    private Short cgyybz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.TBYYBZ
     *
     * @mbg.generated
     */
    private Short tbyybz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.KWYYBZ
     *
     * @mbg.generated
     */
    private Short kwyybz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.PZBZ
     *
     * @mbg.generated
     */
    private Short pzbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.SCBZ
     *
     * @mbg.generated
     */
    private Short scbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.YBCS
     *
     * @mbg.generated
     */
    private Long ybcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.XFCS
     *
     * @mbg.generated
     */
    private Long xfcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.CGCS
     *
     * @mbg.generated
     */
    private Long cgcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLZT.ZLZT
     *
     * @mbg.generated
     */
    private String zlzt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.ZLBH
     *
     * @return the value of YEW_QB_CL_ZLZT.ZLBH
     *
     * @mbg.generated
     */
    public String getZlbh() {
        return zlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.ZLBH
     *
     * @param zlbh the value for YEW_QB_CL_ZLZT.ZLBH
     *
     * @mbg.generated
     */
    public void setZlbh(String zlbh) {
        this.zlbh = zlbh == null ? null : zlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.CGYYBZ
     *
     * @return the value of YEW_QB_CL_ZLZT.CGYYBZ
     *
     * @mbg.generated
     */
    public Short getCgyybz() {
        return cgyybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.CGYYBZ
     *
     * @param cgyybz the value for YEW_QB_CL_ZLZT.CGYYBZ
     *
     * @mbg.generated
     */
    public void setCgyybz(Short cgyybz) {
        this.cgyybz = cgyybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.TBYYBZ
     *
     * @return the value of YEW_QB_CL_ZLZT.TBYYBZ
     *
     * @mbg.generated
     */
    public Short getTbyybz() {
        return tbyybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.TBYYBZ
     *
     * @param tbyybz the value for YEW_QB_CL_ZLZT.TBYYBZ
     *
     * @mbg.generated
     */
    public void setTbyybz(Short tbyybz) {
        this.tbyybz = tbyybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.KWYYBZ
     *
     * @return the value of YEW_QB_CL_ZLZT.KWYYBZ
     *
     * @mbg.generated
     */
    public Short getKwyybz() {
        return kwyybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.KWYYBZ
     *
     * @param kwyybz the value for YEW_QB_CL_ZLZT.KWYYBZ
     *
     * @mbg.generated
     */
    public void setKwyybz(Short kwyybz) {
        this.kwyybz = kwyybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.PZBZ
     *
     * @return the value of YEW_QB_CL_ZLZT.PZBZ
     *
     * @mbg.generated
     */
    public Short getPzbz() {
        return pzbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.PZBZ
     *
     * @param pzbz the value for YEW_QB_CL_ZLZT.PZBZ
     *
     * @mbg.generated
     */
    public void setPzbz(Short pzbz) {
        this.pzbz = pzbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.SCBZ
     *
     * @return the value of YEW_QB_CL_ZLZT.SCBZ
     *
     * @mbg.generated
     */
    public Short getScbz() {
        return scbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.SCBZ
     *
     * @param scbz the value for YEW_QB_CL_ZLZT.SCBZ
     *
     * @mbg.generated
     */
    public void setScbz(Short scbz) {
        this.scbz = scbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.YBCS
     *
     * @return the value of YEW_QB_CL_ZLZT.YBCS
     *
     * @mbg.generated
     */
    public Long getYbcs() {
        return ybcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.YBCS
     *
     * @param ybcs the value for YEW_QB_CL_ZLZT.YBCS
     *
     * @mbg.generated
     */
    public void setYbcs(Long ybcs) {
        this.ybcs = ybcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.XFCS
     *
     * @return the value of YEW_QB_CL_ZLZT.XFCS
     *
     * @mbg.generated
     */
    public Long getXfcs() {
        return xfcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.XFCS
     *
     * @param xfcs the value for YEW_QB_CL_ZLZT.XFCS
     *
     * @mbg.generated
     */
    public void setXfcs(Long xfcs) {
        this.xfcs = xfcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.CGCS
     *
     * @return the value of YEW_QB_CL_ZLZT.CGCS
     *
     * @mbg.generated
     */
    public Long getCgcs() {
        return cgcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.CGCS
     *
     * @param cgcs the value for YEW_QB_CL_ZLZT.CGCS
     *
     * @mbg.generated
     */
    public void setCgcs(Long cgcs) {
        this.cgcs = cgcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLZT.ZLZT
     *
     * @return the value of YEW_QB_CL_ZLZT.ZLZT
     *
     * @mbg.generated
     */
    public String getZlzt() {
        return zlzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLZT.ZLZT
     *
     * @param zlzt the value for YEW_QB_CL_ZLZT.ZLZT
     *
     * @mbg.generated
     */
    public void setZlzt(String zlzt) {
        this.zlzt = zlzt == null ? null : zlzt.trim();
    }
}