package test.serverframe.armc.server.manager.domain;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.List;

public class DatumText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.ZLBH
     *
     * @mbg.generated
     */
    private String zlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.KZDX
     *
     * @mbg.generated
     */
    private Long kzdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.MTGS
     *
     * @mbg.generated
     */
    private String mtgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.WJZS
     *
     * @mbg.generated
     */
    private BigDecimal wjzs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.YS
     *
     * @mbg.generated
     */
    private Long ys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.KZLJ
     *
     * @mbg.generated
     */
    private String kzlj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZLZW.ZWWB
     *
     * @mbg.generated
     */
    private String zwwb;


    @ApiModelProperty("资料")
    private Datum datum;

    @ApiModelProperty(value = "资料附件集合",hidden = true)
    private List<DatumAccessory> accessories;

    @ApiModelProperty("资料互转时用的字段")
    private List<String> zlbhs;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.ZLBH
     *
     * @return the value of QB_GYWB_ZLZW.ZLBH
     *
     * @mbg.generated
     */
    public String getZlbh() {
        return zlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.ZLBH
     *
     * @param zlbh the value for QB_GYWB_ZLZW.ZLBH
     *
     * @mbg.generated
     */
    public void setZlbh(String zlbh) {
        this.zlbh = zlbh == null ? null : zlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.KZDX
     *
     * @return the value of QB_GYWB_ZLZW.KZDX
     *
     * @mbg.generated
     */
    public Long getKzdx() {
        return kzdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.KZDX
     *
     * @param kzdx the value for QB_GYWB_ZLZW.KZDX
     *
     * @mbg.generated
     */
    public void setKzdx(Long kzdx) {
        this.kzdx = kzdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.MTGS
     *
     * @return the value of QB_GYWB_ZLZW.MTGS
     *
     * @mbg.generated
     */
    public String getMtgs() {
        return mtgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.MTGS
     *
     * @param mtgs the value for QB_GYWB_ZLZW.MTGS
     *
     * @mbg.generated
     */
    public void setMtgs(String mtgs) {
        this.mtgs = mtgs == null ? null : mtgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.WJZS
     *
     * @return the value of QB_GYWB_ZLZW.WJZS
     *
     * @mbg.generated
     */
    public BigDecimal getWjzs() {
        return wjzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.WJZS
     *
     * @param wjzs the value for QB_GYWB_ZLZW.WJZS
     *
     * @mbg.generated
     */
    public void setWjzs(BigDecimal wjzs) {
        this.wjzs = wjzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.YS
     *
     * @return the value of QB_GYWB_ZLZW.YS
     *
     * @mbg.generated
     */
    public Long getYs() {
        return ys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.YS
     *
     * @param ys the value for QB_GYWB_ZLZW.YS
     *
     * @mbg.generated
     */
    public void setYs(Long ys) {
        this.ys = ys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.KZLJ
     *
     * @return the value of QB_GYWB_ZLZW.KZLJ
     *
     * @mbg.generated
     */
    public String getKzlj() {
        return kzlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.KZLJ
     *
     * @param kzlj the value for QB_GYWB_ZLZW.KZLJ
     *
     * @mbg.generated
     */
    public void setKzlj(String kzlj) {
        this.kzlj = kzlj == null ? null : kzlj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZLZW.ZWWB
     *
     * @return the value of QB_GYWB_ZLZW.ZWWB
     *
     * @mbg.generated
     */
    public String getZwwb() {
        return zwwb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZLZW.ZWWB
     *
     * @param zwwb the value for QB_GYWB_ZLZW.ZWWB
     *
     * @mbg.generated
     */
    public void setZwwb(String zwwb) {
        this.zwwb = zwwb == null ? null : zwwb.trim();
    }

    public Datum getDatum() {
        return datum;
    }

    public void setDatum(Datum datum) {
        this.datum = datum;
    }

    public List<DatumAccessory> getAccessories() {
        return accessories;
    }

    public void setAccessories(List<DatumAccessory> accessories) {
        this.accessories = accessories;
    }

    public List<String> getZlbhs() {
        return zlbhs;
    }

    public void setZlbhs(List<String> zlbhs) {
        this.zlbhs = zlbhs;
    }
}