package test.serverframe.armc.server.manager.domain;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
import java.util.List;

public class Datum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.ZLBH
     *
     * @mbg.generated
     */
    private String zlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.BT
     *
     * @mbg.generated
     */
    private String bt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.ZTC
     *
     * @mbg.generated
     */
    private String ztc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.MMDJ
     *
     * @mbg.generated
     */
    private String mmdj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.CJR
     *
     * @mbg.generated
     */
    private String cjr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.XGR
     *
     * @mbg.generated
     */
    private String xgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.MGLX
     *
     * @mbg.generated
     */
    private String mglx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.FX
     *
     * @mbg.generated
     */
    private String fx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.HJID
     *
     * @mbg.generated
     */
    private String hjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.FLID
     *
     * @mbg.generated
     */
    private String flid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.ZLLY
     *
     * @mbg.generated
     */
    private String zlly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.FJBS
     *
     * @mbg.generated
     */
    private Short fjbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.KZBS
     *
     * @mbg.generated
     */
    private Short kzbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.CJSJ
     *
     * @mbg.generated
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.XGSJ
     *
     * @mbg.generated
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QB_GYWB_ZL.XH
     *
     * @mbg.generated
     */
    @ApiModelProperty("序号")
    private String xh;

    @ApiModelProperty(value = "批量删除字段", hidden = true)
    private List<String> zlbhs;
    @ApiModelProperty(value = "共展示的附件", hidden = true)
    private Boolean fj;

    @ApiModelProperty(value = "资料附件集合",hidden = true)
    private DatumText datumText;
    @ApiModelProperty("资料类型")
    private DatumType datumType;

    @ApiModelProperty(value = "资料附件",hidden = true)
    private DatumAccessory accessory ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.ZLBH
     *
     * @return the value of QB_GYWB_ZL.ZLBH
     *
     * @mbg.generated
     */
    public String getZlbh() {
        return zlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.ZLBH
     *
     * @param zlbh the value for QB_GYWB_ZL.ZLBH
     *
     * @mbg.generated
     */
    public void setZlbh(String zlbh) {
        this.zlbh = zlbh == null ? null : zlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.BT
     *
     * @return the value of QB_GYWB_ZL.BT
     *
     * @mbg.generated
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.BT
     *
     * @param bt the value for QB_GYWB_ZL.BT
     *
     * @mbg.generated
     */
    public void setBt(String bt) {
        this.bt = bt == null ? null : bt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.ZTC
     *
     * @return the value of QB_GYWB_ZL.ZTC
     *
     * @mbg.generated
     */
    public String getZtc() {
        return ztc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.ZTC
     *
     * @param ztc the value for QB_GYWB_ZL.ZTC
     *
     * @mbg.generated
     */
    public void setZtc(String ztc) {
        this.ztc = ztc == null ? null : ztc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.MMDJ
     *
     * @return the value of QB_GYWB_ZL.MMDJ
     *
     * @mbg.generated
     */
    public String getMmdj() {
        return mmdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.MMDJ
     *
     * @param mmdj the value for QB_GYWB_ZL.MMDJ
     *
     * @mbg.generated
     */
    public void setMmdj(String mmdj) {
        this.mmdj = mmdj == null ? null : mmdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.CJR
     *
     * @return the value of QB_GYWB_ZL.CJR
     *
     * @mbg.generated
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.CJR
     *
     * @param cjr the value for QB_GYWB_ZL.CJR
     *
     * @mbg.generated
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.XGR
     *
     * @return the value of QB_GYWB_ZL.XGR
     *
     * @mbg.generated
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.XGR
     *
     * @param xgr the value for QB_GYWB_ZL.XGR
     *
     * @mbg.generated
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.MGLX
     *
     * @return the value of QB_GYWB_ZL.MGLX
     *
     * @mbg.generated
     */
    public String getMglx() {
        return mglx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.MGLX
     *
     * @param mglx the value for QB_GYWB_ZL.MGLX
     *
     * @mbg.generated
     */
    public void setMglx(String mglx) {
        this.mglx = mglx == null ? null : mglx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.FX
     *
     * @return the value of QB_GYWB_ZL.FX
     *
     * @mbg.generated
     */
    public String getFx() {
        return fx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.FX
     *
     * @param fx the value for QB_GYWB_ZL.FX
     *
     * @mbg.generated
     */
    public void setFx(String fx) {
        this.fx = fx == null ? null : fx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.HJID
     *
     * @return the value of QB_GYWB_ZL.HJID
     *
     * @mbg.generated
     */
    public String getHjid() {
        return hjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.HJID
     *
     * @param hjid the value for QB_GYWB_ZL.HJID
     *
     * @mbg.generated
     */
    public void setHjid(String hjid) {
        this.hjid = hjid == null ? null : hjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.FLID
     *
     * @return the value of QB_GYWB_ZL.FLID
     *
     * @mbg.generated
     */
    public String getFlid() {
        return flid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.FLID
     *
     * @param flid the value for QB_GYWB_ZL.FLID
     *
     * @mbg.generated
     */
    public void setFlid(String flid) {
        this.flid = flid == null ? null : flid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.ZLLY
     *
     * @return the value of QB_GYWB_ZL.ZLLY
     *
     * @mbg.generated
     */
    public String getZlly() {
        return zlly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.ZLLY
     *
     * @param zlly the value for QB_GYWB_ZL.ZLLY
     *
     * @mbg.generated
     */
    public void setZlly(String zlly) {
        this.zlly = zlly == null ? null : zlly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.FJBS
     *
     * @return the value of QB_GYWB_ZL.FJBS
     *
     * @mbg.generated
     */
    public Short getFjbs() {
        return fjbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.FJBS
     *
     * @param fjbs the value for QB_GYWB_ZL.FJBS
     *
     * @mbg.generated
     */
    public void setFjbs(Short fjbs) {
        this.fjbs = fjbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.KZBS
     *
     * @return the value of QB_GYWB_ZL.KZBS
     *
     * @mbg.generated
     */
    public Short getKzbs() {
        return kzbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.KZBS
     *
     * @param kzbs the value for QB_GYWB_ZL.KZBS
     *
     * @mbg.generated
     */
    public void setKzbs(Short kzbs) {
        this.kzbs = kzbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.CJSJ
     *
     * @return the value of QB_GYWB_ZL.CJSJ
     *
     * @mbg.generated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.CJSJ
     *
     * @param cjsj the value for QB_GYWB_ZL.CJSJ
     *
     * @mbg.generated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.XGSJ
     *
     * @return the value of QB_GYWB_ZL.XGSJ
     *
     * @mbg.generated
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.XGSJ
     *
     * @param xgsj the value for QB_GYWB_ZL.XGSJ
     *
     * @mbg.generated
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QB_GYWB_ZL.XH
     *
     * @return the value of QB_GYWB_ZL.XH
     *
     * @mbg.generated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QB_GYWB_ZL.XH
     *
     * @param xh the value for QB_GYWB_ZL.XH
     *
     * @mbg.generated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    public List<String> getZlbhs() {
        return zlbhs;
    }

    public void setZlbhs(List<String> zlbhs) {
        this.zlbhs = zlbhs;
    }

    public DatumText getDatumText() {
        return datumText;
    }

    public void setDatumText(DatumText datumText) {
        this.datumText = datumText;
    }

    public DatumType getDatumType() {
        return datumType;
    }

    public void setDatumType(DatumType datumType) {
        this.datumType = datumType;
    }

    public DatumAccessory getAccessory() {
        return accessory;
    }

    public void setAccessory(DatumAccessory accessory) {
        this.accessory = accessory;
    }

    public Boolean getFj() {
        return fj;
    }

    public void setFj(Boolean fj) {
        this.fj = fj;
    }
}