package test.serverframe.armc.server.manager.domain;

import io.swagger.annotations.ApiModelProperty;

import java.util.List;

public class DatumType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.FID
     *
     * @mbg.generated
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.FLLX
     *
     * @mbg.generated
     */
    private String fllx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.JGID
     *
     * @mbg.generated
     */
    private String jgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.YHID
     *
     * @mbg.generated
     */
    private String yhid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.FLMC
     *
     * @mbg.generated
     */
    private String flmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YEW_QB_CL_ZLFL.FLMS
     *
     * @mbg.generated
     */
    private String flms;

    @ApiModelProperty(value = "资料类型的集合", hidden = true)
    private List<DatumType> children;

    @ApiModelProperty(value = "资料父id", hidden = true)
    private String rootId;

    @ApiModelProperty(value = "资料附件集合",hidden = true)
    private Datum datum;

    @ApiModelProperty(value = "资料的集合", hidden = true)
    private List<Datum> datumList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.ID
     *
     * @return the value of YEW_QB_CL_ZLFL.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.ID
     *
     * @param id the value for YEW_QB_CL_ZLFL.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.FID
     *
     * @return the value of YEW_QB_CL_ZLFL.FID
     *
     * @mbg.generated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.FID
     *
     * @param fid the value for YEW_QB_CL_ZLFL.FID
     *
     * @mbg.generated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.FLLX
     *
     * @return the value of YEW_QB_CL_ZLFL.FLLX
     *
     * @mbg.generated
     */
    public String getFllx() {
        return fllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.FLLX
     *
     * @param fllx the value for YEW_QB_CL_ZLFL.FLLX
     *
     * @mbg.generated
     */
    public void setFllx(String fllx) {
        this.fllx = fllx == null ? null : fllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.JGID
     *
     * @return the value of YEW_QB_CL_ZLFL.JGID
     *
     * @mbg.generated
     */
    public String getJgid() {
        return jgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.JGID
     *
     * @param jgid the value for YEW_QB_CL_ZLFL.JGID
     *
     * @mbg.generated
     */
    public void setJgid(String jgid) {
        this.jgid = jgid == null ? null : jgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.YHID
     *
     * @return the value of YEW_QB_CL_ZLFL.YHID
     *
     * @mbg.generated
     */
    public String getYhid() {
        return yhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.YHID
     *
     * @param yhid the value for YEW_QB_CL_ZLFL.YHID
     *
     * @mbg.generated
     */
    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.FLMC
     *
     * @return the value of YEW_QB_CL_ZLFL.FLMC
     *
     * @mbg.generated
     */
    public String getFlmc() {
        return flmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.FLMC
     *
     * @param flmc the value for YEW_QB_CL_ZLFL.FLMC
     *
     * @mbg.generated
     */
    public void setFlmc(String flmc) {
        this.flmc = flmc == null ? null : flmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YEW_QB_CL_ZLFL.FLMS
     *
     * @return the value of YEW_QB_CL_ZLFL.FLMS
     *
     * @mbg.generated
     */
    public String getFlms() {
        return flms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YEW_QB_CL_ZLFL.FLMS
     *
     * @param flms the value for YEW_QB_CL_ZLFL.FLMS
     *
     * @mbg.generated
     */
    public void setFlms(String flms) {
        this.flms = flms == null ? null : flms.trim();
    }

    public List<DatumType> getChildren() {
        return children;
    }

    public void setChildren(List<DatumType> children) {
        this.children = children;
    }

    public String getRootId() {
        return rootId;
    }

    public void setRootId(String rootId) {
        this.rootId = rootId;
    }

    public Datum getDatum() {
        return datum;
    }

    public void setDatum(Datum datum) {
        this.datum = datum;
    }

    public List<Datum> getDatumList() {
        return datumList;
    }

    public void setDatumList(List<Datum> datumList) {
        this.datumList = datumList;
    }
}